baseURL = "https://marcus.nordaaker.com"
languageCode = "en-us"
title = "Suburban Nerd"
theme = "clean-blog-nord"
copyright = "Code released under the Apache 2.0 license."
disqusShortname = "marcusramberg"
[author]
name = "Marcus Ramberg"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+

[params]
  DateForm = "2006-01-02"
  Description = "Making (?:things|code|evil|mistakes)."
  Author = "Marcus Ramberg"

  email = "marcusramberg@gmail.com"

  # Number of post summaries to show on front page, comment out to allow default(4)
  postSummariesFrontPage = 4

  # Set to false to exclude read time from header of post
  showReadTime = true

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/marcusramberg"
[[params.social]]
  title = "github"
  url = "https://github.com/marcusramberg"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/marcusramberg"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
