baseURL = "https://marcus.means.no/"
languageCode = "en-us"
title = "marcus"
theme = "clean-blog-nord"
copyright = "Code released under the Apache 2.0 license."
disqusShortname = "marcusramberg"
rssLimit = 20
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
[author]
name = "Marcus Ramberg"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+

[params]
  DateForm = "2006-01-02"
  Description = "Making (things|code|mischief|mistakes)."
  Author = "Marcus Ramberg"

  email = "marcus@means.no"

  # Number of post summaries to show on front page, comment out to allow default(4)
  postSummariesFrontPage = 8

  # Set to false to exclude read time from header of post
  showReadTime = false

[[params.social]]
  title = "mastodown"
  url = "https://hachyderm.io/marcus
[[params.social]]
  title = "github"
  url = "https://github.com/marcusramberg"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = -190
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
